# 单位信息配置文件
# 用于配置网站的基本信息、品牌信息等

# 组织信息
organization:
  name: "PromptA"           # 完整组织名称
  logo: "/favicon-96x96.png"       # Logo文件路径（放在 web/public 目录下）
  avatar: "/avatar.jpg"      # 头像文件路径（放在 web/public 目录下）
  login_bg: "/login-bg.jpg"  # 登录背景图片路径（放在 web/public 目录下）

# 项目信息
branding:
  name: "PromptA"
  title: "PromptA: 你的提示词工作中心"     # 系统标题
  subtitle: ""          # 副标题

features:
  - label: ""
    value: "提示词管理"
    description: ""
    icon: ""
  - label: ""
    value: "多模型测试"
    description: ""
    icon: ""
  # - label: ""
  #   value: ""
  #   description: ""
  #   icon: ""
  # - label: ""
  #   value: "智能体集成"
  #   description: ""
  #   icon: ""

actions:
  # - name: "演示视频"
  #   icon: "video"
  #   url: "https://www.bilibili.com/video/BV1DF14BTETq"
  # - name: "文档中心"
  #   icon: "docs"
  #   url: "https://xerrors.github.io/Yuxi-Know/"
  # - name: "提交 Issue"
  #   icon: "issue"
  #   url: "https://github.com/xerrors/Yuxi-Know/issues/new/choose"
  # - name: "开发路线图"
  #   icon: "roadmap"
  #   url: "https://xerrors.github.io/Yuxi-Know/latest/changelog/roadmap.html"



# 页脚信息
footer:
  copyright: "© PromptA 2026 v0.0.1"
